### ISSUE TITLE
Geolocation board view

### ISSUE THREAD

**Issue by PimDeWitte** [crisisboard/opencrisisboard#21]
As a user, you should be able to view a board from a text-first approach and a map-first approach for different use cases. For instance, if you are on a board focused on delivery grocery to elderly, you will want to see where these requests originate from before you scroll through all the requests. 

We're suggesting a UX similar to airbnb - although we have no direct UX mockups at this time. Ideas welcome.

**Comment by EdenCoder** [comment]
I'll finish this one up

**Comment by EdenCoder** [comment]
Also show the bar for geolocation even if browser geolocation is available

**Comment by PimDeWitte** [comment]
<img width="1440" alt="Screen Shot 2020-03-21 at 4 35 12 PM" src="https://user-images.githubusercontent.com/8763534/77239937-84300b00-6b9d-11ea-9160-02ad219faad0.png">

**Comment by asaki444** [comment]
@PimDeWitte  @EdenCoder  for this, upon loading the page, there should be tickers on the map to show where each request is? And the left should display the information about these requests? 

Should the top also have a filter by time/date of request as well?

**Comment by aPruner** [comment]
Just in case people are busy, and since this is a demo-critical feature, I'll have a go at this one in parallel with whoever else is curerently working on it :)

**Comment by EdenCoder** [comment]
@aPruner this would be perfect if you can, I've been under the gun with a bunch of other work recently.

**Comment by EdenCoder** [comment]
@aPruner will be taking over this one for now

**Comment by aPruner** [comment]
POC is done and the full PR is coming soon! Here's a screenshot of the feature in action (can upload a video if necessary):

<img width="1125" alt="MapView Screenshot" src="https://user-images.githubusercontent.com/16375966/77804133-0f951a80-703c-11ea-9f67-9e69a466cbbe.png">

NOTE: this is a very tricky feature UX-wise, as there are so many elements that I still need to add to it such as:
- Pre-centering the map (do it based on user-location, or based on areas where posts are dense?, I think user-location is fine for now, so that's what I plan on doing)
- Disabling the map view on mobile browsers (and adding some other way to access it on mobile)
- Adding a map toggle (also determining the behaviour of this toggle on mobile)
- Determining what information in the tooltip is necessary (for now, the discussion title, link to the discussion, and author I think should be good enough)
- Colouring the map Pin (or Marker) and tooltip accordingly so it contrasts enough from the background of the map (or changing the map colour itself)

**Comment by aPruner** [comment]
Completed and merged in PR #31
